<<<<<<< HEAD
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
=======
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";

const inter = Inter({ subsets: ["latin"] });
>>>>>>> 8f66f2bbe97bcd190f2d707eb70fc7773ecc459e

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en" data-theme="light">
      <body className={roboto.className}>
        <Navbar />
        {children}
=======
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
          {children}
        </div>
>>>>>>> 8f66f2bbe97bcd190f2d707eb70fc7773ecc459e
      </body>
    </html>
  );
}
